src/pages/Top/Components/PolymerCoat/index.module.scss, src/pages/top/components/ReviewComment/index.module.scss, src/pages/top/components/ReviewSlider/index.module.scss, src/pages/top/components/Reviewer/index.module.scss
=> includeの名前直した

src/pages/top/components/ReviewSlideImage/index.module.scss
=> rename responsive name

src/components/SpNavMenu/index.tsx, src/pages/top/components/ReviewSlideImage/index.module.scss
=> toppage組み込み時に発生した今回の作業とは無縁のerrorを入れてます

src/pages/top/components/PricingPlan/index.module.scss
=> styled letterSpacing of priceSection min-price

src/pages/top/components/ReviewSlider/index.module.scss
=> styled overflow of review component

src/pages/top/components/LiquidCardSwipe/index.module.scss
=> liquid component restyle

src/pages/top/components/LiquidCardSwipe/index.module.scss
=> styled liquid card padding

src/pages/top/components/TopView/index.module.scss
=> fixed width of top view component

src/components/Footer/index.module.scss, src/components/Footer/index.tsx
- footerのpaddingを調整したのだ
- PC修正前
- PC修正後
- SP修正前
- PC修正後
=> Changed padding for footer component

src/components/BeforeAfterSpCard/index.module.scss, src/components/ButtonLink/index.module.scss, src/components/FixedBottomContact/index.module.scss, src/components/FooterDescription/index.module.scss, src/components/SectionTitle/index.module.scss, src/components/SpNavMenu/index.module.scss, src/pages/_document.page.tsx, src/pages/top/components/FAQItem/index.module.scss, src/pages/top/components/LiquidCard/index.module.scss, src/pages/top/components/PricingPlan/index.module.scss, src/pages/top/components/Reviewer/index.module.scss, src/pages/top/components/TopView/index.module.scss, src/pages/top/components/VerticalText/index.module.scss, src/styles/globals.scss
=> Noto sans JP聞いてない問題解消

src/pages/top/components/VerticalText/index.module.scss
=> 💡 styled vertical text

src/components/Footer/index.module.scss, src/const/footerNav.ts
=> Footerの表示崩れ直したよん

src/components/BeforeAfterSpCard/index.module.scss
=> ビフォアフの意図していないFontを直した

src/pages/top/components/TopView/index.module.scss, src/pages/top/index.module.scss
=> topviewのスタイル修正

src/components/FixedBottomContact/index.module.scss, src/components/Header/index.module.scss, src/pages/index.page.tsx, src/pages/top/index.module.scss
=>  placed component at top

src/components/Footer/index.module.scss, src/pages/top/index.module.scss
=>  add padding footer bottom

src/pages/top/components/TopView/index.module.scss
=>  restyled top view padding

src/pages/top/components/VerticalText/index.module.scss, src/pages/top/index.module.scss
=> 💡 paddingの調整

src/components/Logo/index.module.scss, src/components/PcNavMenu/index.module.scss, src/pages/top/components/WorksHeroImageDescription/index.module.scss, src/pages/top/components/WorksSlider/index.module.scss, src/pages/top/hooks/useWorksSliderBreakPointsStyle.ts, src/pages/top/index.module.scss
=> works slide image size

src/pages/top/components/ReviewComment/index.module.scss, src/pages/top/hooks/useReviewSliderBreakPointStyle.ts
=> resized image of review slide

src/pages/top/components/WorksHeroImageDescription/index.module.scss
=> worls leftの修正

src/const/navMenu.ts, src/pages/index.page.tsx, src/pages/works/index.page.tsx
=> ディレクトリの追加と、リンクの追加

src/pages/top/components/TopViewAutoImageSlide/index.module.scss, src/pages/works/components/TopView/const/worksTopViewImageList.ts, src/pages/works/components/TopView/index.module.scss, src/pages/works/components/TopView/index.stories.tsx, src/pages/works/components/TopView/index.tsx, src/pages/works/index.page.tsx
https://d-base-hp.atlassian.net/browse/SCRUM-163
- create works topview slider
=> completed topView slider of works page

src/pages/top/components/TopViewAutoImageSlide/index.module.scss, src/pages/works/components/TopView/const/worksTopViewImageList.ts, src/pages/works/components/TopView/index.module.scss, src/pages/works/components/TopView/index.stories.tsx, src/pages/works/components/TopView/index.tsx, src/pages/works/index.module.scss, src/pages/works/index.page.tsx
https://d-base-hp.atlassian.net/browse/SCRUM-162
- built in header component
=> built in header works

src/pages/works/components/ProcessTitle/index.module.scss, src/pages/works/components/ProcessTitle/index.stories.tsx, src/pages/works/components/ProcessTitle/index.tsx
=>  process title completed style and refactor

src/pages/works/components/ProcessDescription/index.module.scss, src/pages/works/components/ProcessDescription/index.stories.tsx, src/pages/works/components/ProcessDescription/index.tsx
=> process component finished sp pc

src/pages/_app.page.tsx, src/pages/app.module.scss, src/pages/index.page.tsx, src/pages/top/index.module.scss, src/pages/works/index.module.scss, src/pages/works/index.page.tsx
- headerとfooterを_app.page.tsxに移動しました。
=> changed header footer page to app

src/pages/price/components/StarLevel/index.module.scss, src/pages/price/components/StarLevel/index.stories.tsx, src/pages/price/components/StarLevel/index.tsx, src/pages/price/logics/craftRating.ts
- create rating component
- create craft rating logic
- refactoring
=> create Rating component and create rating logic

src/pages/price/components/PriceCardText/index.module.scss, src/pages/price/components/PriceCardText/index.stories.tsx, src/pages/price/components/PriceCardText/index.tsx
=> create card text component

src/pages/price/components/PriceCardText/index.module.scss, src/pages/price/components/PriceCardText/index.stories.tsx, src/pages/price/components/PriceCardText/index.tsx, src/pages/price/components/SizeCardText/index.module.scss, src/pages/price/components/SizeCardText/index.stories.tsx, src/pages/price/components/SizeCardText/index.tsx
=> price card size text

src/pages/price/components/PriceCard/const/priceCardList.ts, src/pages/price/components/PriceCard/index.module.scss, src/pages/price/components/PriceCard/index.stories.tsx, src/pages/price/components/PriceCard/index.tsx, src/pages/price/components/PriceCardText/index.module.scss
=> feat: 🎸 create price card

src/pages/price/components/CraftTitle/index.module.scss, src/pages/price/components/CraftTitle/index.stories.tsx, src/pages/price/components/CraftTitle/index.tsx, src/styles/variables.scss
https://d-base-hp.atlassian.net/browse/SCRUM-177
- SP版
- PC版
=> craft-title作成

src/pages/price/components/PriceCard/const/priceCardList.ts, src/pages/price/components/PriceCard/index.module.scss, src/pages/price/components/PriceCard/index.stories.tsx, src/pages/price/components/PriceCard/index.tsx, src/pages/price/components/PriceCardList/index.module.scss, src/pages/price/components/PriceCardList/index.stories.tsx, src/pages/price/components/PriceCardList/index.tsx, src/pages/price/components/PriceCardText/index.module.scss, src/pages/price/components/PriceCardText/index.tsx
=> price list section

package.json, pnpm-lock.yaml, src/pages/price/components/CarDrawerList/index.tsx, src/pages/price/components/PriceCard/const/priceCardList.ts
=> install uuid

src/const/footerNav.ts, src/const/navMenu.ts, src/pages/index.page.tsx, src/pages/top/components/FaqSection/index.tsx, src/pages/top/logics/generateSlideStyle/index.ts
=> change a pass

src/components/Footer/index.module.scss
=> add hover animation to Footer

src/const/footerNav.ts, src/const/navMenu.ts
=> built contact page
